export const GET_ALL_POKEMONS = 'GET_ALL_POKEMONS';
export const FILTERS = 'FILTER_BY_TYPE';
export const PAGINATION = 'PAGINATION';
export const GET_ALL_TYPES = 'GET_ALL_TYPES';
export const POKEMON_BY_ID = 'POKEMON_BY_ID';
export const DELETE_DETAILS = 'DELETE_DETAILS';